### ISSUE TITLE
recommendation for taxonomic coverage?

### ISSUE THREAD

**Issue by ymgan** [biodiversity-aq/data-publication#3]
Do we follow recommendations from INBO for [taxonomic coverage](https://github.com/biodiversity-aq/data-publication/wiki/Coverage-and-keywords#taxa)?

See: https://github.com/inbo/data-publication/wiki/Coverage-and-keywords#taxa

**Comment by Antonarctica** [comment]
I think we should give priority to the OBIS guidelines with a modification for terrestrial that is more like INBO.

**Comment by Antonarctica** [comment]
Taxa

Adding taxa needs to be done mostly manually which can be time-consuming. Detailed partitions of the taxonomy are generated by GBIF and OBIS on a dataset page, so it is not useful to manually provide (and maintain) the full taxonomic coverage of a dataset here. 

Useful things to mention:
Kingdom(s) included in the dataset
Phylum(s) included in the dataset
Lower taxonomic ranks until the number of groups at a rank exceeds 10
The English vernacular names (use the register of Antarctic Species) in lowercase and with & for combinations of names, e.g.: lanternfish, seastars & brittle stars
The (limited number of) species with specific sampling focus, if applicable
